// ⚠️  THIS FILE IS AUTO-GENERATED by FlutterFire CLI.
//
// DO NOT write this file manually. Follow the setup steps in README.md
// to generate it automatically for your Firebase project.
//
// Run this command after creating your Firebase project:
//   flutterfire configure
//
// That command will replace this file with real config for Android, iOS & Web.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace with flutterfire configure output
    throw UnsupportedError(
      'Run `flutterfire configure` to generate firebase_options.dart. '
      'See README.md for full setup instructions.',
    );
  }
}
